### ISSUE TITLE
error when using sdss bandpasses and model with mw extinction

### ISSUE THREAD

**Issue by lisaleemcb** [sncosmo/sncosmo#100]
The functions <code>model.bandmag()</code> and <code>model.color()</code> throw an exception when sdss bandpasses are specified and a sn model is initialized with mw extinction.  It appears that this is because the sdss wavelengths are not the expected dtype.  This is shown <a href="https://gist.github.com/lisaleemcb/8a12cb621a931efba1d4"> here </a>.

**Comment by kbarbary** [comment]
:fireworks: Issue 100! :fireworks: You win a prize!

Thanks for the detailed report. This is happening because the Cython code for color laws only supports arrays of `float64`: https://github.com/sncosmo/sncosmo/blob/master/sncosmo/_extinction.pyx#L73

But I think the fix should be to simply ensure that wavelengths in bandpasses are always `float64`, when the Bandpass is constructed. I'll look into it.

**Comment by dannygoldstein** [comment]
What does she win?

**Comment by kbarbary** [comment]
@dannygoldstein The respect and thanks of the open-source community. :)
