### ISSUE TITLE
Licensing requirements of adding Dependencies to SNCosmo

### ISSUE THREAD

**Issue by rbiswas4** [sncosmo/sncosmo#104]
@kbarbary
One of the things @nkarp is interested in is the possibility of using Multinest within SNCosmo. This could be used, for example, as another good methods of sampling posteriors within SNCosmo, and applied to light curves parameters, but to other places as well. I am aware of licensing issues in doing this. 

It would be great if you could say a few things about 
- the philosophy behind licensing
- If people want to play with a different piece of code(say, a different sampler for SNCosmo lightcurve models for example), which does not have the appropriate license, what are the possible options, and how would one like them to proceed.

**Comment by kbarbary** [comment]
I'm glad you brought this up because (1) I always forget the details of the Multinest license and (2) it brings up the issue of better documentation for using alternative samplers.

## Multinest License

Many pixels have been spilled over licensing philosophy, so I won't go into any great detail about philosophy, per-se. There is an excellent recent [blog post by C. Titus Brown](http://ivory.idyll.org/blog/2015-on-licensing-in-bioinformatics.html) on the subject. There are several relevant links in the post, including [Jake Vanderplas's post on licensing scientific code](http://www.astrobetter.com/blog/2014/03/10/the-whys-and-hows-of-licensing-scientific-code/) and a [post about a piece of software with a license similar to Multinest](http://www.homolog.us/blogs/blog/2015/05/18/pachters-kallisto-comes-with-unconventional-license/). If I had to hazard a one-sentence summary of the above links, it would be that non-open-source software should be avoided, and that among open-source licenses more permissive ones (such as MIT or BSD) are highly preferred over less permissive ones (such as GPL).

Now, what is the situation with Multinest? It has a [license [PDF]](http://www.mrao.cam.ac.uk/~ff235/MultiNest_License.pdf) that is definitely not open-source. In short, the license has three strikes against it:

- It is a custom, **non-standard** license, making it legally much more ambiguous in several ways I won't go into here.
- The license is for **non-commercial use only**, which already makes it not open-source by any definition I know.
- The license has a specific clause that **limits redistribution rights**:

  ```
  4. User may modify the Software and distribute that modified work to third
  parties provided that: [...] (c) User agrees to notify FF&MH of the distribution,
  and (d) User clearly notifies secondary users that such modified work is not
  the original Software. 
  ```

Even if it weren't for this last point, I would still be opposed to the Multinest license, but the requirements on redistribution makes it particularly problematic: The license makes it practically infeasible to widely repackage and redistribute Multinest and even makes it unclear under what *name* it can be redistributed.

Possibly as a side effect of the difficulty of redistribution, the Python wrapper for Multinest is [not easy to install](http://johannesbuchner.github.io/PyMultiNest/install.html), even on Linux. It is particularly impossible on Windows. SNCosmo (and any optional dependencies) should be installable with one command; there's no reason it should be any harder.

I would LOVE LOVE LOVE to use Multinest in sncosmo, but until it has a license as permissive as the LGPL (or preferably BSD or MIT), we have to limp along with our own pale (but *open-source*) [imitation](http://github.com/kbarbary/nestle).


## Using Multinest and SNCosmo together

All the above are reasons for not using Multinest within SNCosmo. That said, it is perfectly possible for someone to use the two together, and in fact, SNCosmo has been designed with this in mind. (Though it isn't yet explicitly documented.) Basically, one can define a likelihood for a set of light curve data given any sncosmo model, and that likelihood can be fed to any fitter or sampler you want. The function `sncosmo.chisq(data, model)` can be used for this. Looking [under the hood](https://github.com/sncosmo/sncosmo/blob/v1.1.x/sncosmo/fitting.py#L45) of that function, you can see that the definition is basically:

```python
mflux = model.bandflux(data['band'], data['time'],
                       zp=data['zp'], zpsys=data['zpsys'])
return np.sum(((data['flux'] - mflux) / data['fluxerr'])**2)
```

In other words, "use the model to predict the flux in the given bandpasses and times (scaled with the appropriate zeropoint), then use those values to calculate the chisq." So really `Model.bandflux()` is the key method.

How do you actually define the likelihood? Different fitters or samplers have different requirements for the interface for the likelihood (or posterior) function. In the case where the function must accept an array of parameter values, it can be defined like this:
```python
    def loglikelihood(parameters):
        model.parameters[:] = parameters  # set model parameters
        return -0.5 * sncosmo.chisq(data, model)
```

Of course, this will vary *all* the parameters in the model, which might not be what you want. To only vary select parameters, you could do something like this:

```python
    # Indicies of the model parameters that should be varied
    idx = np.array([model.param_names.index(name)
                    for name in param_names_to_vary])

    def loglikelihood(parameters):
        model.parameters[idx] = parameters
        return -0.5 * sncosmo.chisq(data, model)
```
See [here](https://github.com/sncosmo/sncosmo/blob/v1.1.x/sncosmo/fitting.py#L593-L598) for an example of this in the sncosmo code.

The functions `sncosmo.fit_lc()`, `sncosmo.mcmc_lc()` and `sncosmo.nest_lc()` are just wrappers around external fitters and samplers (respectively, iminuit, emcee, and a custom nested sampling code). The wrappers themselves don't do anything too complex -- just stuff like setting guesses, bounds and providing a consistent interface. My hope is that anyone can do the same thing with whatever samplers they like. In fact, I'd like to see more fitters and samplers explored.

I hope this helps. I think this explanation about how to use a custom sampler should be turned into a section in the sncosmo docs.

**Comment by kbarbary** [comment]
MIT-licensed Nestle with multi-ellipsoid sampling method is now available via pip. See http://kbarbary.github.io/nestle for details.

Still leaving this issue open until there are docs in sncosmo on using custom samplers.
