### ISSUE TITLE
plot_lc for tables with mag and magerr?

### ISSUE THREAD

**Issue by dannygoldstein** [sncosmo/sncosmo#116]
In my fork of `sncosmo`, I wrote a reader function `_read_csp` that reads photometry files released by CSP and returns tables like this:

```python
In [4]: sncosmo.read_lc('SN2006luopt+nir_photo.dat', format='csp')
Out[4]:
<Table masked=False length=134>
    mjd      filter   magerr   mag
  float64   string64 float64 float64
----------- -------- ------- -------
 54040.3211        u   0.026  18.793
 54040.3211        B   0.011  18.059
 54040.3211 V_LC9844    0.01  17.911
 54040.3211        g   0.007  17.919
 54040.3211        r   0.009  17.893
 54040.3211        i   0.017  18.473
54041.35904        Y   0.098  19.016
54042.32148        u   0.035  19.011
54042.32148        B    0.01  18.184
54042.32148 V_LC9844   0.011  17.987
54042.32148        g   0.009  18.031
54042.32148        r   0.012  17.968
54042.32148        i    0.02  18.583
54043.31674        Y   0.146  19.264
54043.31674        J   0.542  19.806
  54044.365        r   0.021  18.045
  54044.365        i   0.046   18.69
        ...      ...     ...     ...
54121.27083 V_LC9844   0.036  20.918
54121.27083        g   0.037  21.348
54121.27083        r   0.028  20.749
54121.27083        i   0.068  21.245
 54125.2998        B    0.06  21.739
 54125.2998 V_LC9844   0.042  20.956
 54125.2998        g   0.036  21.296
 54125.2998        r   0.035  20.886
 54125.2998        i   0.094  21.202
54130.21164        g   0.081  21.484
54130.21164        r   0.051  20.982
54130.21164        i   0.126   21.15
54131.24436 V_LC9844   0.065  21.029
54131.24436        r   0.056  21.033
54543.12044        Y    0.29  21.354
54838.24365        Y   0.245  21.474
54838.24365        J   0.435  21.792
54838.24365        H   0.741  19.715
```

I would like to plot these light curves using `plot_lc`, but this requires that the lcs be in flux space. Is there any deep reason for not allowing `plot_lc` to plot magnitudes?

**Comment by kbarbary** [comment]
Mostly that it doesn't conform to the [data model](http://sncosmo.readthedocs.org/en/latest/photdata.html#column-names-and-units) for photometric data in sncosmo. [Also, as shown, there is no magnitude system information in your table, but I'm sure you could add it somehow. Magnitude system information *is* required for plot_lc, so that photometric data can be plotted against models or other photometric data.]

The idea with the data model is that any table that conforms to that model should be usable in `fit_lc`, `nest_lc`, `mcmc_lc`, `write_lc`, etc. It would be weird to make a table in magnitudes work for `plot_lc`, but not all the other functions that do things with photometry.

There are two possible solutions:

1. Have `sncosmo.read_lc(..., format='csp')` output a table in flux space (one that conforms to the data model). This is probably the easiest.

2. Make the sncosmo photometric data model more complicated, allowing a magnitude representation and errors in magnitude space.

Note: the option to *display* light curves in magnitudes in `plot_lc` is a separate issue. It's certainly possible, just no one has requested it yet. However, I think it is orthogonal to the issue of *representing* the data.

**Comment by kbarbary** [comment]
Is CSP format documented somewhere, btw? seems like your reader would be useful to have.

**Comment by rbiswas4** [comment]
I guess this is a little late for @dannygoldstein . But similar issues might be relevant for other datasets. For CSP, I guess they use Snoopy and it seems to have  a data reader function:
http://users.obs.carnegiescience.edu/cburns/SNooPyDocs/html/
get_sn()

Is it worth importing that and doing the interface to snosmo data_model format? Or should we try to write readers independently? From a practical side, this depends on whether the data format or the code output is likely to be more stable, but also issues about dependencies are important.

**Comment by dannygoldstein** [comment]
@kbarbary, the reader function is here: dannygoldstein/sncosmo@1dc8ff68

**Comment by dannygoldstein** [comment]
@rbiswas4, version 2.0 of `snpy` appears to be incompatible with version 1.10.0 of `numpy`, as `snpy` depends on the `numpy.oldnumeric` module, which was deprecated in `numpy` 1.9.0: 

http://docs.scipy.org/doc/numpy/reference/routines.oldnumeric.html

**Comment by dannygoldstein** [comment]
As of 01ea4df, I can do:

```python 
In [1]: import sncosmo
/home/blanco/code/miniconda2/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)

In [2]: lc = sncosmo.read_lc('SN2005elopt+nir_photo.dat', format='csp')

In [3]: fig = sncosmo.plot_lc(lc)

In [4]: fig.show()
```

and get:

![sn2005el](https://cloud.githubusercontent.com/assets/2769632/11026391/f98ed994-8687-11e5-8c3f-17b170c7d8d0.png)
