### ISSUE TITLE
MLCS2k2 fluxfile

### ISSUE THREAD

**Issue by MichelleLochner** [sncosmo/sncosmo#121]
Hi guys

I want to use Saurabh's new code for my research but I'm not sure what to do with the fluxfile MLCS2k2. Is it this Hsiao file here
`sncosmo/sncosmo/data/models/Hsiao_SED_V3_subsampled.fits`
or something else?

If so, I get a ValueError when trying to read from that file.

**Comment by kbarbary** [comment]
Does `sncosmo.get_source('mlcs2k2')` work for you? It's a built-in so the file should be downloaded automatically. (Assuming you're using master.)

**Comment by MichelleLochner** [comment]
Yes that worked! So it seems it's not yet set up to automatically download the source file like the other models (I didn't see mlcs2k2 listed among the models), but using
`sncosmo.get_source('mlcs2k2')` and then
`mod=sncosmo.Model('mlcs2k2')` works perfectly. Thanks!

**Comment by kbarbary** [comment]
`mod = sncosmo.Model('mlcs2k2')` should also automatically download the file. (Internally it calls `get_source`.) Glad it's working though.

'mlcs2k2' is listed on this page http://sncosmo.readthedocs.org/en/latest/builtins/sources.html at the bottom of the table. (You have to go to the "latest" docs, since its not in a released version yet.)

**Comment by MichelleLochner** [comment]
Ok thanks @kbarbary! Maybe I misspelt it or something. I'll have a look at the latest docs. Thanks again!
