### ISSUE TITLE
`pip install` failure on travis

### ISSUE THREAD

**Issue by rbiswas4** [sncosmo/sncosmo#135]
I tried to install sncosmo on travis using the 
`pip install --no-deps sncosmo`
method but it seems that it cannot be imported:

The log is available at https://api.travis-ci.org/jobs/135520483/log.txt?deansi=true

What I am seeing is that 
`import sncosmo`
fails after the pip install.

(I believe the other errors are inconsequential)

Are people using pip installs of sncosmo in travis tests?

**Comment by kbarbary** [comment]
Here's a guess: you installed pip into the root conda environment, but then created a `test` environment that doesn't have pip. Therefore, when you `pip install`, you're getting the system pip, not the conda pip, so everything you `pip install` is going into the system directories, and then python doesn't find it because you're using the conda python.

Try installing pip into the conda test environment before any pip commands.

**Comment by rbiswas4** [comment]
Ok will try. And does this mean that using SNCosmo on travis necessarily needs a conda environment because of astropy.config? Before this I had tried a pip based installation (with no conda involved) and that had failed because of astropy.config not being available (even though astropy was installed through the pip). It seemed from astropy, that the way to avoid that was to use astropy.helpers.

**Comment by rbiswas4** [comment]
By the way, even if I use conda install, I get this problem: the log is at

https://s3.amazonaws.com/archive.travis-ci.org/jobs/135524071/log.txt .

Maybe this means that I still have to source some setup file to get the conda python rather than using the system python

**Comment by kbarbary** [comment]
Install nose into the conda environment as well. When you run `nosetests`, its picking up the system nose, which uses the system python.

That might fix it, but there's still something weird: when you run `python setup.py install --user` on your package, it is installing your package into the system directories. I would have expected it to either install into `$HOME/.local/lib` (since you passed the `--user` flag) or the conda directory, since the conda python is presumably being used.

Anyway, this doesn't look like an sncosmo problem. I suspect you'd have the same problem importing, e.g., numpy. sncosmo just happens to be the first dependency imported in your tests.

**Comment by kbarbary** [comment]
> Maybe this means that I still have to source some setup file to get the conda python rather than using the system python

At some point you did `source activate test` and get the log output:

```
discarding /home/travis/miniconda/bin from PATH
prepending /home/travis/miniconda/envs/test/bin to PATH
```

That should be all you need. Hence my comment above that I expect the conda python is presumably being used by the time you setup.py install your package.

**Comment by rbiswas4** [comment]
OK. I used these ideas and was able to get travis working with both pip and conda installs of sncosmo.

For reference, these working directories are:
- pip : https://github.com/rbiswas4/sncosmo_lc_analysis/tree/testpip https://github.com/rbiswas4/sncosmo_lc_analysis/commit/ba1e8c32e0e467e35c55ecafe523dbb6c154d9ea
- conda: https://github.com/rbiswas4/sncosmo_lc_analysis/commit/4ba21e3a275c2c6275ba6791dc48e756484867fd
I plan to develop on the conda branch, but not on the pip branch, which I am keeping just as reference.
