### ISSUE TITLE
Salt2-extended model cannot generate flux

### ISSUE THREAD

**Issue by Samreay** [sncosmo/sncosmo#138]
The cl values found when initialising an extended salt 2 source cause the clbase values to reach infinity, breaking the Spline interpolation used in the calculation of flux, causing flux values to all return NaN.

**Comment by kbarbary** [comment]
I think this is a subtle Python 3 unicode bug that has completely broken all SALT2 models. :open_mouth: 

Arising from the fact that in Python 3:
```
In [3]: b'Salt2ExtinctionLaw.version' == 'Salt2ExtinctionLaw.version'
Out[3]: False
```
At the very least, the extinction law version is being set incorrectly to v0 instead of v1 in `SALT2Source._set_colorlaw_from_file`.

I've been avoiding using online data (e.g., the SALT2 data files) in tests, but this is evidence that it is really needed.

**Comment by Samreay** [comment]
Ah, python three unicode, breaking everything yet again. The amount of
grief it caused me when I was trying to fix PolyChord is insane. Is there a
simple work around that I could employ in sncosmo at the moment, or are you
planning on putting a patch out and know the fix?

Cheers

**Comment by kbarbary** [comment]
It's the first time I'm glad that more people are not already on Python 3.

I'll try to fix it tomorrow.

**Comment by kbarbary** [comment]
Can you give master a try now?

**Comment by Samreay** [comment]
Awesome, thanks Kyle

**Comment by Samreay** [comment]
Im reinstalling it from git now. Will check the extended model and report back.

**Comment by Samreay** [comment]
Alright, done a basic test, and it didnt fall over like it used to! Cheers
