### ISSUE TITLE
difference in supernova fluxes between versions

### ISSUE THREAD

**Issue by AlexGKim** [sncosmo/sncosmo#166]
I noticed another peculiar difference between v.1.3.2 and v1.4, in the integrated flux of a supernova, that I don't think can be explained by a resampling of integrals.

The input code is

```python
#!/usr/bin/env python
import numpy
import sncosmo

print sncosmo.__version__

lams = numpy.array([4795.35,5780.60])

name='V'

synbands=sncosmo.Bandpass(lams, [1.,1.], name='tophat'+name)

model_nodust = sncosmo.Model(source='hsiao')
flux_nodust = model_nodust.bandflux(synbands,0.)
print flux_nodust
```

and the outputs are

```
(test) tibia:gerard akim$ ./test.py
1.3.2
1903056.82396
```

```
tibia:gerard akim$ ./test.py
1.4.0
962718.069375
```

**Comment by kbarbary** [comment]
Is there some reason you don't think this can be explained by the new improved sampling? 1000 Angstroms is a pretty big gap; a SN spectrum varies a lot in that range so I can see the old behavior being off by a factor of 2.

**Comment by kbarbary** [comment]
I tried to verify that one could recover this difference in sncosmo v1.4.0 by setting `sncosmo.models.MODEL_BANDFLUX_SPACING` to some very large value. However, with a large value ( > 1000) the result becomes `856320.765571`, only a difference of about 10% from the initial value of `962718.069375`. I'll have a deeper look into this later.

**Comment by kbarbary** [comment]
There is another change in how bandpasses are treated in v1.4.0 that is causing this difference. In v1.3.2, the bandpass datapoints were treated as "bins". For example, a wavelength of 4795.35 and transmission of 1.0 was taken to describe the *center* of a bin and its height. The width of the bin was calculated from the spacing of the bins. So in this example we have two bins of height 1.0 and width 985.25.

In v1.4.0, the points are taken to be samples of a continuous function, which is zero outside the extrema of the samples. This is likely the definition you expected in this case.

Here's an illustration of the difference (I've set the transmissions to `[0.9, 0.95]` instead of `[1.0, 1.0]`):

![tmp](https://cloud.githubusercontent.com/assets/970135/20653845/53226a92-b4e1-11e6-9f5c-d879b035d1d6.png)

So effectively the bandpass was twice as wide in v1.3.2, resulting in approximately twice the flux.

There would not be nearly as much of a difference between v1.3.2 and v1.4.0 for better sampled bandpasses (any real-world measured bandpass); you can see how these two plots would converge when more samples are added.

**Comment by rbiswas4** [comment]
@kbarbary As you point out the difference will be small for the bandpasses we will want to use, but if I understand correctly, the interpolation will still happen. Is this somehow being cached, so that it does not result in a speed hit (at the expense of a very slightly more correct result) for real bandpasses?

**Comment by kbarbary** [comment]
No caching is being done (yet). We can evaluate whether it would be worthwhile to implement.
