### ISSUE TITLE
sncosmo.Model object is not picklable 

### ISSUE THREAD

**Issue by jpierel14** [sncosmo/sncosmo#192]
I'm in the process of using the python multiprocessing package with sncosmo. During multiprocessing, the objects being returned need to be pickled. I've found that an sncosmo model object is not picklable due to the source inside of the model. For example:

```
import sncosmo
import pickle

model=sncosmo.Model('salt2')
model._source=None
with open('test.pkl','wb') as handle:
    pickle.dump(model,handle)
```

This fails. I've been able to workaround it by setting the source to None during the pickle, and then replacing it later, i.e.:

```
import sncosmo
import pickle

model=sncosmo.Model('salt2')
model._source=None
with open('test.pkl','wb') as handle:
    pickle.dump(model,handle)
```

This succeeds, but isn't elegant and is potentially causing other problems. Any way to make the sncosmo.Model object picklable?

**Comment by kbarbary** [comment]
Looks like you're working off of sncosmo master, not the release version? Indeed, the latest implementation of `SALT2Source` is not pickleable (though other sources should be). We should make this work.

Background for the interested reader: The dev version includes a custom interpolator used in `SALT2Source` called [`BicubicInterpolator`](https://github.com/sncosmo/sncosmo/blob/910cdd32fbd10771d96b21527812bc50fce2457c/sncosmo/salt2utils.pyx#L93), implemented in Cython. C extension types (Cython cdef classes) are not automatically pickleable without some extra implementation. This is because the data in the instance is hidden from the Python layer.

It should be possible to make `BicubicInterpolator` pickleable, but I'm having trouble finding good docs on how to do it at the moment!

**Comment by kbarbary** [comment]
Also, [`SALT2ColorLaw`](https://github.com/sncosmo/sncosmo/blob/910cdd32fbd10771d96b21527812bc50fce2457c/sncosmo/salt2utils.pyx#L339) will need to be made pickleable as well.

**Comment by rbiswas4** [comment]
This probably does not directly answer your question, but might be useful if you are looking at parallelizing SNCosmo analyses: I don't use the multiprocessing package directly, but I have been using `joblib.Parallel` without any trouble on `sncosmo: version1.5.dev750` which in default seems to use the `multiprocessing` backend:
https://pythonhosted.org/joblib/parallel.html#parallel-reference-documentation
```
class joblib.Parallel(n_jobs=1, backend=None, verbose=0, timeout=None, pre_dispatch='2 * n_jobs', batch_size='auto', temp_folder=None, max_nbytes='1M', mmap_mode='r')
...
```
```
backend: str, ParallelBackendBase instance or None, default: ‘multiprocessing’
Specify the parallelization backend implementation. Supported backends are:
“multiprocessing” used by default, can induce some communication and memory overhead when exchanging input and output data with the worker Python processes.
“threading” is a very low-overhead backend but it suffers from the Python Global Interpreter Lock if the called function relies a lot on Python objects. “threading” is mostly useful when the execution bottleneck is a compiled extension that explicitly releases the GIL (for instance a Cython loop wrapped in a “with nogil” block or an expensive call to a library such as NumPy).
finally, you can register backends by calling register_parallel_backend. This will allow you to implement a backend of your liking.
```

**Comment by kbarbary** [comment]
So, pickling should work now, but with a caveat: Pickling protocols 0 and 1 *don't* work, so on Python 2 (where the default is 0) you have to specify `protocol=2` in `pickle.dump`. Hopefully `multiprocessing` uses protocol 2!

**Comment by jpierel14** [comment]
Just wanted to close this out by saying that Multiprocessing does use protocol 2 by default, and with your update the pickling works and Multiprocessing operates successfully, thanks a lot!
