### ISSUE TITLE
sncosmo.select_data() does not work on covariance if column is already named 'fluxcov'

### ISSUE THREAD

**Issue by drhay53** [sncosmo/sncosmo#213]
In sncosmo 1.5.3, if using a covariance matrix in the data table, the column must be named one of the aliases or select_data skips it due to not being in the alias_map (line 232 of photdata.py).

**Comment by kbarbary** [comment]
Oops. I think `'fluxcov'` should be included in the set on [this line](https://github.com/sncosmo/sncosmo/blob/f6072158cae1d1a463e21e2ac914a67798f0185d/sncosmo/photdata.py#L28). Want to make a PR?

**Comment by drhay53** [comment]
Sure, I can do it. 

One somewhat related question is that a situation occurred where it would have been useful to run select_data on a PhotometricData object. Or also, to turn a PhotometricData object back into an astropy table. 

Is PhotometricData not really intended to be used by the general user? What are your thoughts on a PR (someday?)

**Comment by kbarbary** [comment]
That's right, `PhotometricData` is meant to be [internal only](https://github.com/sncosmo/sncosmo/blob/f6072158cae1d1a463e21e2ac914a67798f0185d/sncosmo/photdata.py#L35), which is why it doesn't appear (or shouldn't appear!) in any docs. It's used internally to standardize the variety of column names and input types that sncosmo allows for data tables.

I thought about making it part of the public facing API. The main drawback was that users would want to manipulate the data (e.g., removing rows), so `PhotometricData` would then have to re-implement many of the table operations of astropy `Table`, or inherit from `Table`. In the end it seemed like it didn't make a lot of sense and would only complicate things by having another table-like class that users needed to learn how to use.
