### ISSUE TITLE
Future of Spectrum class in sncosmo

### ISSUE THREAD

**Issue by kboone** [sncosmo/sncosmo#262]
One of the many things that sncosmo does very well is synthetic photometry. It has a huge range of different filters implemented, and there is a great framework for taking arbitrary spectral timeseries and turning them into synthesized photometry in arbitrary bands and at arbitrary times.

However, right now, all of this is somewhat internal to sncosmo. There isn't an easy way to leverage all of these tools for spectra or spectral time series that are outside of sncosmo, especially data from actual telescopes that are noisy and that come in all sorts of different formats. There is some basic support for synthetic photometry in the undocumented Spectrum class that I know several groups have used for real observed spectra, but it is very limited and I don't think that it is officially supported.

Is there interest in expanding on the synthesized photometry functionality in sncosmo, and is that within the scope of the project? I would be interested in developing the Spectrum class so that they can be applied to actual data. I have an (incomplete) PR in #259 that is one step towards that, allowing for uncertainties on the spectra to be propagated into the photometry. This functionality would be extremely valuable for the SNfactory data that will soon be released. Developing a full Spectrum class could also be used to build the foundation for spectral timeseries mangling discussed in #56 among other things.

Going one step further, the synthetic photometry routines in sncosmo could have a lot of applications even outside of the supernova community. Would it make sense to turn them into a separate package or move them into something upstream? The only similar package that I am aware of is [synphot](https://synphot.readthedocs.io/en/latest/), but it has somewhat of a different philosophy, and it doesn't have all of the bands built-in like sncosmo does.

**Comment by kbarbary** [comment]
I haven't forgotten this! There are a number of aspects to the story here.

The `Spectrum` class in sncosmo has an interesting history. It actually used to support uncertainties in flux and at one point, propagated those uncertainties in synthetic photometry. This was deprecated in v1.4 and finally removed in v2.0 (see [here](https://github.com/sncosmo/sncosmo/commit/a430c058697a122b3928a8143e6541e87000e36a#diff-fec1b6773c95455bb67b2c7473b95761)). You can see it also used to support redshifting.

The reason for the removal boiled down to this: the only place the class was being explicitly used in sncosmo was in `SpectralMagSystem`. For that use case, we weren't using the uncertainties. And in fact, we essentially wanted not an "observed" spectrum, but a "model" spectrum: a continuous 1-d function rather than binned counts. (Yes, the spectra are not quite truly that ideal, but we use them that way). The `Spectrum` class was trying to fulfill both roles: (1) being a container for a model, and (2) being a container for data. We only needed the model role, so we got rid of the rest.

So the `Spectrum` class could really be renamed `SpectrumModel` or some such. I think if we were to represent a data spectrum we would do it in a completely separate class. I think there's an analgous divide between the `SourceModel` classes and `PhotData`: one is a model of a continuous 2-d surface in `(wavelength, time)` and the other is a container for observations of that surface (binned in certain ways). 

(As an aside, the error stuff was kinda poorly done and poorly tested anyway: the error propagation assumed no covariance between flux measurements, which I think is rarely true.)

I think there was some interest at some point in a class to contain *actual* spectral data. It would be needed if we were going to have the ability to fit models to spectral data, for one. This was something that I discussed with @cmsaunders at some point.

**Comment by kboone** [comment]
Thanks, this is very interesting.

I agree that the separation between something like `SpectrumModel` and `SpectrumData` (or whatever you want to call them) would make a lot of sense. The PR that I wrote then definitely would belong in `SpectrumData`.

I'll think about what makes sense for a `SpectrumData` class that contains real spectral data. One important thing is that it needs to be aware of where the bins for each spectral element are. A model spectrum doesn't need to care about that. Your point that the error propagation needs to include covariance is a very good one, and that is probably difficult to handle in a consistent way. I'm guessing that very few telescopes even have a good model of the covariance between wavelength bins...

**Comment by cmsaunders** [comment]
I have a local branch where I have made a `SpectroscopicData` class modeled on the `PhotometricData` class and have added a function modeled on `fitlc` to fit a model to spectroscopic data. I think @sam-dixon has independently written something similar. I can't remember if there was anything blocking me from doing a pull request--maybe just that I hadn't finished documentation. I can push it to github if there is interest.

**Comment by kboone** [comment]
That sounds great. I would be happy to look at what you have and help however I can to get it in sncosmo.

**Comment by sam-dixon** [comment]
I wound up reimplementing a lot of `fitlc` myself and have my own synthetic photometry code, but never wrapped anything up nicely enough to fit into sncosmo. I'd also be happy to take a look at a PR and contribute some tests.

**Comment by kboone** [comment]
I changed the title because it seems like this discussion is implying that we really need a better version of the Spectrum class. If either of you wants to start a PR, go for it. I'm also happy to take your code as is and start trying to figure out how to fit it in to sncosmo if that is helpful.

**Comment by kbarbary** [comment]
This might be a good first use case for an enhancement proposal: github.com/sncosmo/sncosmo-eps. Just to discuss concrete design before implementing a bunch of code.

**Comment by cmsaunders** [comment]
Ok, I decided to just make a draft pull request for my branch spectra_fitter: https://github.com/sncosmo/sncosmo/pull/265. There is a spectral time series fitter and a spectroscopic data class in it. I made some comments on the current status of the code on the draft PR page.

**Comment by kboone** [comment]
I finally got a chance to look into this, and I'm going to put an EPS together. Thanks for this PR @cmsaunders, your implementation of fitting spectral time series looks pretty much complete. The SpectroscopicData class is also something that we could use more generally for spectra and add functionality like synthetic photometry to.

Thinking more about this, there are several different scenarios where you might want to include spectra in fitting. For example, you might have a single spectrum near maximum light along with a light curve. It would be good if we could handle all different combinations of photometry/spectra with a single set of fitting routines. This could be accomplished by merging the functionality in chisq_sts/fit_sts into chisq/fit_lc (which are mostly identical anyway). We would need a way to input both photometry and spectra simultaneously into these functions which will require some thought for the API.

**Comment by kboone** [comment]
This was addressed in #269.
