### ISSUE TITLE
Spectrum not included in API reference docs

### ISSUE THREAD

**Issue by kbarbary** [sncosmo/sncosmo#297]
I noticed that the `Spectrum` class (introduced in v2.2.0) doesn't appear in the reference docs https://sncosmo.readthedocs.io/en/latest/reference.html. Although it is nicely explained in https://sncosmo.readthedocs.io/en/latest/spectrum.html.

A separate but related documentation issue: I have encountered a bit of confusion about the Spectrum docs, which I think is due to the example of creating a Spectrum from a model:
```python
>>> flux = model.flux(time=sample_time, wave=wave)

>>> spectrum = sncosmo.Spectrum(wave, flux, time=sample_time)
```
we may want to change the example to load the wavelength and flux arrays from a file (or a helper function like `load_example_data()`) to emphasize that the `Spectrum` class is designed for storing observed data rather than a model.

**Comment by kboone** [comment]
I fixed this in #298. I agree that the model stuff was confusing. I added a new `load_spectrum_example_data` function that returns example `wave`, `flux`, and `fluxerr` arrays so that we can get rid of all of the model code. There is a new script called `gen_example_spectrum.py` that is what I used to generate the example spectrum, and it is basically just a copy of what used to be in the docs.
