### ISSUE TITLE
Function(s) to load public SN datasets

### ISSUE THREAD

**Issue by kbarbary** [sncosmo/sncosmo#59]
as suggested by @jakevdp

**Comment by jakevdp** [comment]
I'd be happy to hack on this – any ideas about where they might be stored on the web?

**Comment by kbarbary** [comment]
The SDSS-SNLS joint lightcurve analysis (JLA) might be a good data set to start with. It looks like they have the full light curve for each SN in there:

http://supernovae.in2p3.fr/sdss_snls_jla/ReadMe.html

**Comment by rbiswas4** [comment]
Yes :), but there is also the union compilation http://supernova.lbl.gov/Union/descriptions.html#FullTable
All SDSS data is at http://sdssdp62.fnal.gov/sdsssn_data/Papers/DataRelease/WebPage/  I suppose PanStarrs and CSP are also public.

This should come with some warning in SNCosmo because there is a danger than one may fit these data directly with SNCosmo functions. The JLA data probably requires updated bandpasses https://github.com/sncosmo/sncosmo/issues/10 for accurate work.

**Comment by kbarbary** [comment]
Unfortunately, I don't think the Union full light curves are published, with the exception of the SCP-observed SNe (a vast minority of the Union sample). Still, it would be useful to get the SCP observed SNe from there.

+1 on the PS1 sample and CSP samples.

Have to be careful about sample overlap when people combine samples and release them as one dataset.

And yes, agree that we still need a good API solution for position-dependent bandpasses, and a warning until that happens.

**Comment by rbiswas4** [comment]
And what one could do to play with data would be to download SNANA SNDATA_ROOT and find light curves from the directory lcmerge.

**Comment by kbarbary** [comment]
FYI: I'm working on this in http://github.com/kbarbary/sndatasets After I make more progress there, it may make sense to merge into sncosmo proper.

**Comment by kbarbary** [comment]
Any work on this is going to remain in http://github.com/sncosmo/sndatasets so I'm closing this.
