### ISSUE TITLE
sncosmo.write_lc()

### ISSUE THREAD

**Issue by rbiswas4** [sncosmo/sncosmo#61]
Request:
1. write_lc should include a fits format.  
2. It should be possible to stack multiple SN lcs (say as a list of tables) into such a fits format easily

**Comment by kbarbary** [comment]
1. I investigated FITS files for single SN light curves, thinking it would be faster and more compact (as its a binary format). It turns out that its actually slower and more space-consuming than ASCII formats. The slower part might have to do with the overheads in `astropy.io.fits`, but I'm not sure. The space part has to do with the minimum size of a FITS header, which is pretty big. My conclusion is that we should not bother writing individual SN light curves to separate FITS files.
 
2. Writing sets of SN light curves to FITS might be a different story. There's code for doing this in dessn/des-sn-dbscripts in the `get-des-lightcurves` script. The format is similar to SNANA FITS except that there is just a single FITS file with two HDUs. Interested in putting this into a new sncosmo function?

3. An alternative to investigate for this is using HDF5 via h5py. We could push people into the modern world of binary storage formats....

**Comment by rcthomas** [comment]
Inside-outify serialization.  Expose the data model for LCs and make sure
it can be understood by anyone.  Delegate serialization of it to
astropy-based (or not even) methods for users who absolutely need HDF5 or
FITS or whatever.  Keeping a default ASCII serialization in your library
though makes a lot of sense for SN LCs.  Do less work.

Rollin

On Fri, Jan 16, 2015 at 11:44 AM, Kyle Barbary <notifications@github.com>
wrote:

>
>    1.
>
>    I investigated FITS files for single SN light curves, thinking it
>    would be faster and more compact (as its a binary format). It turns out
>    that its actually slower and more space-consuming than ASCII formats. The
>    slower part might have to do with the overheads in astropy.io.fits,
>    but I'm not sure. The space part has to do with the minimum size of a FITS
>    header, which is pretty big. My conclusion is that we should not bother
>    writing individual SN light curves to separate FITS files.
>    2.
>
>    Writing sets of SN light curves to FITS might be a different story.
>    There's code for doing this in dessn/des-sn-dbscripts in the
>    get-des-lightcurves script. The format is similar to SNANA FITS except
>    that there is just a single FITS file with two HDUs. Interested in putting
>    this into a new sncosmo function?
>    3.
>
>    An alternative to investigate for this is using HDF5 via h5py. We
>    could push people into the modern world of binary storage formats....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sncosmo/sncosmo/issues/61#issuecomment-70310420>.
>



-- 
Dr. R. C. Thomas
Computational Cosmology Center
Lawrence Berkeley National Lab
1 Cyclotron Road Mail Stop 50B4206
Berkeley, California 94720-8151
510.486.4697

**Comment by rbiswas4** [comment]
1. The space issue jives with what I was seeing last week trying to get small fits files for your tests. 
2. Ok ... it might be good to get that into sncosmo. (Obviously, once it is there, one could also write a single light curve, so maybe we should have  a note discouraging that. 
3. Personally, I am open to HDF5. I have played with this using h5py and pandas, but have not used any small files.

**Comment by kbarbary** [comment]
@rcthomas Agreed. The data model should at least be clear: each LC is simply a astropy.Table object (with certain required column names).

Also of note is that astropy has a proposal for a fairly sane ASCII table standard that includes header info in the same file as the table. In the future, we could just use this instead of my ad-hoc crappy format that `write_lc` defaults to. See astropy/astropy-APEs#7 .

**Comment by rbiswas4** [comment]
@rcthomas 

1. I think the data model is quite clear, so it is already at the stage you are suggesting. Users can already write them out in any way they like. 
2. I think there is some merit in having a nice serialization, without forcing it on anyone. That way, (a) not everyone has to reinvent the wheel, and (b) we don't necessarily have to differ on equivalent formats and have extra steps while working with one another.

**Comment by kbarbary** [comment]
What's the to-do item here? I don't really like the idea of providing a FITS writer for multiple LCs. It would work, but just feels wrong.

For HDF5, one can already write individual astropy Tables to HDF5 groups (http://astropy.readthedocs.org/en/latest/io/unified.html#hdf5), so it would be pretty trivial to wrap that up to write multiple tables to the same file, indexed by name. If someone is willing to test the performance and usability of this and implement a `write_lcs` function, I'd support such a PR.

**Comment by rbiswas4** [comment]
I think we could do a test of performance in the next few weeks both for light curves and analysis results. @lisaleemcb has implemented (at least in initial form) something that writes results to hdf5, which is useful for analysis methods using SNCosmo. I think it would be useful to figure out how well these work, and we can decide later whether this should be added to SNCosmo or stay in a user codes using SNCosmo (as @rcthomas ) suggests, with easy links to obtain them

**Comment by kbarbary** [comment]
Closing this for now as not actionable, but feel free to re-open with a more detailed proposal.
