### ISSUE TITLE
sncosmo.plot_lc() documentation

### ISSUE THREAD

**Issue by rbiswas4** [sncosmo/sncosmo#64]
The current documentation http://sncosmo.readthedocs.org/en/latest/api/sncosmo.plot_lc.html
seems to suggest that zp, zpsys are optional parameters. However, it seems that if I try this using 
sncosmo.plot_lc(data) where data does not have zp or zpsys column, this fails. Related to this, is the fact that the minimal columns required for data should be listed here.

**Comment by kbarbary** [comment]
The `zp` and `zpsys` keyword arguments in `plot_lc` refer to the *displayed* zeropoint and zeropoint system, rather than the contents of the data. The data, as throughout sncosmo, is required to have zp and zpsys columns. The reason we need to specify the *displayed* zeropoint system is that the data points in a given band might not all be normalized to the same zeropoint system. In order to display them coherently in flux space, we need to first perform that normalization. But what zeropoint and zeropoint system should we normalize them to? Well, the default is zp = 25 in the AB system (somewhat arbitrarily!). But the user can change this via the keywords.

It sounds like we need a bit more verbose documentation of the `zp` and `zpsys` keywords, and a pointer to the existing documentation on the required data format, here: http://sncosmo.readthedocs.org/en/latest/photdata.html. Do you think you can make a PR?

**Comment by rbiswas4** [comment]
ok.

**Comment by kbarbary** [comment]
Closed via 1f07966aea2b0deb21354ea809847e8274f0a421
