### ISSUE TITLE
plot_lc doesn't close figures, resulting in MPL RuntimeWarning

### ISSUE THREAD

**Issue by drhay53** [sncosmo/sncosmo#75]
When looping over many light curves and saving figures with plot_lc, after ~20 MPL spits out a RuntimeWarning since the figures are never closed. 

    RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_num_figures`). max_open_warning, RuntimeWarning)

**Comment by kbarbary** [comment]
I don't think there's much more we can do here, except perhaps better documentation. Here's exactly what happens:

* If you specify the `fname` keyword argument, the figure is saved to that file name and it *is* closed. Nothing is returned (or more precisely, `None` is returned).
* If you don't specify `fname`, the figure itself is returned. Since we're returning the figure for the user to do something with, we can't close it within `plot_lc`. However, the latest docs do say:
```
fig : matplotlib Figure
    Only returned if fname is None. Display to screen with plt.show() or save
    with fig.savefig(filename). When creating many figures, be sure to close
    with plt.close(fig).
```
You might not have seen that if you were looking at the default docs page (v0.4).

Any ideas for what could be better in terms of behavior or docs?

**Comment by drhay53** [comment]
Ah yes, my mistake. I was not passing fname because I wanted to actually show the plot, and then, as I usually do, I changed my local plt.show() to plt.savefig(). So this is totally on my end. Sorry about that.

Is there any way for plot_lc to not use a new figure every time? I guess a plt.gcf() in sncosmo.plotting won't be the previously generated figure? 

My only comment about the docs, and it's minor, is that the plotting module seems robust enough to have it's own sidebar section. The current doc is clear about closing your own figures.

**Comment by kbarbary** [comment]
I agree there could be a page about plotting (other than the reference/API page). I always find myself looking for a "plotting" page on the sidebar!

I'm not exactly sure how `plt.gcf()` works, but we wouldn't want overwriting the current figure to be the default: it would mess up multi-page PDFs (see last example in `plot_lc` docs). We could allow the user to pass in an existing `Figure` as an option, and use that. However, we'd have to check that the figure size is correct; might cause more confusion than it alleviates.

**Comment by drhay53** [comment]
I don't think any new changes are warranted based on this experience, and I'm happy to close the issue. I think this is partially an issue with my continued lack of discipline in handling MPL figures.
