### ISSUE TITLE
Fitting Photometric API empty

### ISSUE THREAD

**Issue by lisaleemcb** [sncosmo/sncosmo#94]
The [Fitting Photometric API page](http://sncosmo.readthedocs.org/en/latest/reference.html#fitting-api), in the documentation, seems to be empty for the latest version.  The previous version looks okay.

**Comment by kbarbary** [comment]
Oh yeah, I just noticed that the other day. Will have a look.

**Comment by kbarbary** [comment]
This is apparently due to a bug in Sphinx 1.3, now widely reported: sphinx-doc/sphinx#1822. There's a fix already proposed in sphinx, so hopefully the fix will be in the next released sphinx version (presumably 1.3.3). Unfortunately I think we'll just have to wait for that release, and then for readthedocs to update to it.

The work-around seems to be hand-writing the table of functions, which doesn't seem worth it at this point (assuming the fix will be released soonish).

**Comment by kbarbary** [comment]
Found a much easier work-around in 9c629b6a0c. Seems to be fixed.
