### ISSUE TITLE
better bandpass treatment

### ISSUE THREAD

**Issue by kbarbary** [sncosmo/sncosmo#99]
The bandpasses included with sncosmo as "built-ins" are sometimes "down-sampled" and "truncated" if their sampling is too fine or they cover a large wavelength range. It would be good to be able to:
- store the raw bandpass definitions
- take care of down-sampling & truncation in software (when loading bandpass)
- add multiple versions of a bandpass while we're at it(?)

_edit:_ Having the raw (full) bandpass definitions will give better provenance as well.
### Background
- **Down-sampling** is reducing the wavelength resolution of the bandpass. This is done simply for performance reasons: when integrating a SN spectrum through a bandpass, we need to chose some wavelength grid on which to evaluate the spectrum and the bandpass. Currently, we just use the wavelengths at which the bandpass is defined. This makes evaluating the bandpass simple - no interpolation necessary! However, the time it takes to do an integral scales linearly with the number of bandpass samples, so we don't want to sample more finely than necessary. In practice, a resolution of 5 Angstroms in wavelength is usually good (and is incidentally what SALT2/snfit uses).
- **Truncation** is reducing the wavelength coverage of the bandpass at low and high wavelengths. Practically, many bandpass definitions include a huge range of wavelengths where the transmission is zero or very nearly so, as a measurement of "out-of-band" transmission. This is of interest for some studies. For us, this wide wavelength coverage usually just hurts performance (simply because there are more samples; see above) and causes problems with model wavelength coverage: the model is only defined over a finite wavelength range, and we require that the bandpass definition not extend past the model. A wider bandpass makes this more difficult (or limits the range of redshifts where we can integrate the model through the bandpass).

**Comment by PaulKuin** [comment]
For UV filters you need to have the red tail, as even 1% red leak, once the UV flux drops steeply, will give a substantial contribution. To deal with this you probably need a quick and dirty method to estimate that effect, then choose your sampling based on the effective band (the flux times transmission as a function of wavelength).

**Comment by rcthomas** [comment]
Kyle, can you point to where you do the integral in the code?  Don't get excited, I probably don't have anything bright to say about it...

**Comment by kbarbary** [comment]
@rcthomas See [this line](https://github.com/sncosmo/sncosmo/blob/c4b2bf7ae76a4ad3bd821a7b4ee378d2520cde75/sncosmo/models.py#L134).

@PaulKuin That's a good thing to keep in mind, thanks. It would be good to find a way to be more rigorous and systematic about this, even if that involves some approximation (as you say). Including the full bandpass definition will be the first step I think.

**Comment by rcthomas** [comment]
This could be taken down to a single vector multiply and sum if you made a cached property in Bandpass that pre-multiplied the bandpass stuff together once, along with the divide-by constant.  That will speed up the integral itself but I don't think it means you won't still want to down-sample.  The integral itself is probably much subdominant to things like sampling the model (line above), which can't be amortized away because the redshift and other model parameters may change between calls (unless you know they are fixed).

**Comment by rbiswas4** [comment]
This is about the truncation problem:
- The usual SALT2 spectra are within a limited range of wavelength. So estimating what we might be missing out for SN at different redshifts is hard.
- The 'salt2-extended' model has a wider wavelength range. So, this could be used to estimate the change in flux due to truncation. Is there a (or a few) SN spectrum measured to large wavelength ranges which may be a better template to use for such a calculation?

**Comment by kbarbary** [comment]
@rcthomas Right. I benchmarked this at some point and determined that the model spline interpolation was indeed dominant. It would be good to re-check this at some point though.

**Comment by rbiswas4** [comment]
@rcthomas @kbarbary 

I did a quick check on times required to evaluate the model flux (using the `model.flux(time, band) `at the bandpass samples  and the times to calculate bandfluxes `model.bandflux(time, band)` using the same model and bands. I used the salt2-extended model to prevent out of band problems.

What I am seeing is that 
- Obviously the time for both is larger when the number of bandpass samples is larger.
- `model.flux`  step done independently needs between 80 and 95 percent of the time required to obtain bandfluxes through `model.bandflux`.

It would seem that this is happening at the stage that the 2D model surface is being interpolated to obtain the model surface at desired time and wavelengths, rather than evaluating the model at their native wavelengths and times, but I have not tested that . So presumably, if we are to imaging speedups, this is where it should be.

**Comment by kbarbary** [comment]
@rbiswas4 Yes, that matches my experience when developing the code. As far as I can tell, there isn't a *lot* of room for improvement in the model spline interpolation, but I'd love to be proven wrong here! Under the covers, the interpolation code uses `scipy.interpolate.RectBivariateSpline`, which is a fairly thin wrapper around a Fortran library for 1-d and 2-d splines. I'm not aware of any faster spline libraries, but I also haven't looked around that much.

**Comment by rbiswas4** [comment]
@kbarbary I don't know either, but would be useful to ask around, given how integral these interpolations are to the whole setup.

Wondering aloud: Would it help if we only did a phase interpolation on the model surfaces and did a wavelength interpolation on the bands to match the model native wavelengths?

- In the most general case, we might be able to gain slightly from the fact that the bandpasses are smoother than spectra, so maybe easier to interpolate?
- But in the often used case (even though it is never really there) where redshift is 'known', this implies that for different model parameters used in fitting such a light curve, the wavelengths would be the same, so we would not have to interpolate the bandpasses every time. How much this would shave off, I have no idea. 

Having said that: I love having model.flux and being able to get the SED at any time, by interpolating in both variables.

**Comment by rcthomas** [comment]
@kbarbary @rbiswas4 If a bandpass can have a configurable (but default-valued) down-sampled version of its original sampling and carry its original sampling as well, then you could do the following.  Model fitting and so on could be done with the down-sampled version first (and by default) and then when all is said and done a final integral pass on the converged values with full sampling could be done, and the difference propagated forward, or trigger warnings and such.  Like "that is too much vermouth."

**Comment by kbarbary** [comment]
@rbiswas4 In most cases we *have* to interpolate the model in wavelength. Many models are not sampled finely enough in wavelength. For example, SALT2 is only sampled every 10 Angstroms (and will be more in observer frame).

In the case of fitting for fixed redshift, large speed gains are possible, as one could evaluate all the model components just once. However, in practice this is difficult to implement in a clean way that works for all models. I'm open to trying something like this though.

@rcthomas interesting idea. Reminds me of how numeric intergration routines return an error estimation along with their answer. Regardless of whether we implement that in integration, I do think bandpasses should carry their original sampling and a configurable down-sampled version, all in memory, as you suggest.

**Comment by rbiswas4** [comment]
@rcthomas 
I think a bandpass class with *a* configurable down-sampled version (with default parameters) should not be hard to set up and is a good idea. Generating useful and appropriate warnings is harder but can come in good time. In terms of performance, this can help a lot for densely sampled bandpasses, but will probably not help a lot if someone has already provided some decent downsampling. 

As an example I downsampled and truncated the LSST filters to a reasonable range, and a 5 Ang grid, and got about a 10x speedup on bandflux,  But going down to 10 Ang grid did not give much gains beyond that, and at some point we will start making larger errors. Hence pushing on the model interpolation is probably a good thing to try.

**Comment by kbarbary** [comment]
Yes, this issue is not really about improving performance (we already have ~5 Angstrom sampling for most bandpasses and thats probably a good trade-off sampling). This is more about correctness, consistency and provenance.
